development:
  host: "http://gentle-refuge-4246.herokuapp.com/"
  fb_key: "502056609805917"
  fb_picture: "http://s3-ap-northeast-1.amazonaws.com/ulabla-image/logo.png"
  fb_caption: "http://bit.ly/bamboo_forest"
  app_name: "대나무숲"

production:
  host: "http://gentle-refuge-4246.herokuapp.com/"
  fb_key: ENV['FB_KEY']
  fb_picture: "http://s3-ap-northeast-1.amazonaws.com/ulabla-image/logo.png"
  fb_caption: "http://bit.ly/bamboo_forest"
  app_name: "대나무숲"
